// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlagController from "./flag_controller"
application.register("flag", FlagController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertQuestionController from "./insert_question_controller"
application.register("insert-question", InsertQuestionController)

import MapController from "./map_controller"
application.register("map", MapController)
